from MinecraftWS import Event
from dev.ucyt.indigomod.indigomod.pip import *
from dev.ucyt.indigomod.indigomod.print import *
def handle(event):
    if event == Event.BlockBroken:
        ...
    elif event == Event.MenuShown:
        ...
    elif event == Event.BlockPlaced:
        ...
    elif event == Event.AdditionalContentLoaded:
        ...
    elif event == Event.AgentCommand:
        ...
    elif event == Event.WorldGenerated:
        ...
    elif event == Event.MultiplayerRoundStart:
        ...
    elif event == Event.ApiInit:
        ...
    elif event == Event.WorldUnloaded:
        ...
    elif event == Event.AppPaused:
        ...
    elif event == Event.AppResumed:
        ...
    elif event == Event.AppSuspended:
        ...
    elif event == Event.BossKilled:
        ...
    elif event == Event.CameraUsed:
        ...
    elif event == Event.EndOfDay:
        ...
    elif event == Event.ConnectionFailed:
        ...